"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](fg:grey)\
$os\
[](fg:grey bg:blue)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green bg:grey)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
[](fg:grey bg:white)\
$kubernetes\
[▓▒░](fg:white)\
$line_break\
$character"""

palette = 'p10k_default'

[palettes.p10k_default]
grey = "#444444"
light_grey = "#6c6c6c"
blue = "#005faf"
green = "#5fd700"
yellow = "#d7af00"
red = "#d70000"
white = "#e4e4e4"
black = "#000000"

[os]
disabled = false
style = "bg:grey fg:white"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "bg:blue fg:white"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"


[git_branch]
symbol = ""
format = "[ $symbol $branch ](fg:#2a2a2a bg:green)"

[git_status]
format = "[($staged$modified$untracked$renamed$deleted$stashed$ahead_behind )](fg:#2a2a2a bg:green)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
stashed = "\\$${count}"
modified = "~${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
untracked = "?${count}"

[nodejs]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[bun]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[c]
symbol = " "
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[rust]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[golang]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[php]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[java]
symbol = " "
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[kotlin]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[haskell]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version) ]($style)"

[python]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $version)(\\(#$virtualenv\\)) ]($style)"

[docker_context]
symbol = ""
style = "bg:grey fg:white"
format = "[ $symbol( $context) ]($style)"

[conda]
symbol = "  "
style = "bg:grey fg:white"
format = "[$symbol$environment ]($style)"
ignore_base = false

[kubernetes]
disabled = false
symbol = "☸"
style = "bg:white fg:black"
format = "[ $symbol $context( \\($namespace\\)) ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:green)"
vimcmd_replace_one_symbol = "[❮](bold fg:blue)"
vimcmd_replace_symbol = "[❮](bold fg:blue)"
vimcmd_visual_symbol = "[❮](bold fg:yellow)"
