
[env]
TERM = "xterm-256color"

[window]
decorations = "full"
title = "Alacritty"

  [window.dimensions]
  columns = 100
  lines = 25

  [window.padding]
  x = 6
  y = 6

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 5_000

[font]
size = 16

  [font.normal]
  family = "MesloLGS NF"
  style = "Regular"

  [font.bold]
  family = "MesloLGS NF"
  style = "Bold"

  [font.italic]
  family = "MesloLGS NF"
  style = "Italic"

  [font.bold_italic]
  family = "MesloLGS NF"
  style = "Bold Italic"

  [font.offset]
  x = 1
  y = 1

[colors.primary]
background = "#002b36"
foreground = "#93a1a1"

[colors.cursor]
text = "#002b36"
cursor = "#b1c1b1"

[colors.normal]
black = "#002b36"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#6c71c4"
cyan = "#2aa198"
white = "#f0f0f0"

[colors.bright]
black = "#657b83"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#6c71c4"
cyan = "#2aa198"
white = "#fdf6e3"

[[colors.indexed_colors]]
index = 16
color = "#cb4b16"

[[colors.indexed_colors]]
index = 17
color = "#d33682"

[[colors.indexed_colors]]
index = 18
color = "#073642"

[[colors.indexed_colors]]
index = 19
color = "#586e75"

[[colors.indexed_colors]]
index = 20
color = "#839496"

[[colors.indexed_colors]]
index = 21
color = "#eee8d5"
